# This file may be used to create a conda environment using:
#   $ conda env create --prefix=${HOME}/miniconda3/envs/dplvn3p12 --file environment.yml
# Modding PYTHONPATH seem to break things (zstandard errors, invocation of wrong Python):
#   $ conda env config vars set PYTHONPATH=${HOME}/miniconda3/envs/dplvn3p12/lib/python3.12/site-packages
name: dplvn3p12
channels:
  - conda-forge
dependencies:
  - python=3.12
  - meson
  - pybind11
  - ninja
  - twine
  - numpy
  - jupyter
  - ipython
  - matplotlib  