name: Upload Python Package to TestPyPI

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine
          
      - name: Build package
        run: |
          python -m build

      - name: Upload distribution
        uses: actions/upload-artifact@v4
        with:
          name: main-dist
          path: dist/

  publish-to-testpypi:
    runs-on: ubuntu-latest
    needs:
      - build-main
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    environment:
      name: testpypi
      url: https://testpypi.org/project/dplvn

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: main-dist
          path: dist/

      - name: Publish release distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          repository_url: https://test.pypi.org/legacy/
          password: ${{ secrets.pypi-AgENdGVzdC5weXBpLm9yZwIkMzJmYjg2N2QtYzc0Ni00NjljLThmNGUtOWI0NzA3NWM4M2NkAAIqWzMsIjcxZTFhYmFkLTg3NTktNDdhOC05NDgwLTg3OTAyNzYyZGM2MiJdAAAGIG2Oy2iZTX0nWmdrsH1kfATaNHHWMAh-vyEUQF3sxwIm }}
          skip_existing: true # Optional: prevents errors if package already exists
